name: lancaster
version: 0.0.1
author: Ernesto Carrella <ernesto.carrella@gmail.com>
description: A monopolistic competition model that would hopefully run straight into the paper. Supposedly inspired by the Lancaster models of competition.
dependencies:
  angular:
    git: https://github.com/angular/angular.dart.git
  browser: any
  charted: any
  paper_elements: any
  json_object: any
dev_dependencies:
  mockito:
    git: https://github.com/fibulwinter/dart-mockito.git
  unittest: any
transformers:
- angular