name: lancaster
version: 0.0.1
author: Ernesto Carrella <ernesto.carrella@gmail.com>
description: A monopolistic competition model that would hopefully run straight into the paper. Supposedly inspired by the Lancaster models of competition.
dependencies:
  angular: 1.0.0
  browser: any
  observe: any
  charted: any
  perf_api: 0.0.9
dev_dependencies:
  mockito:
    git: https://github.com/fibulwinter/dart-mockito.git
  unittest: any
transformers:
- angular:
     html_files:
      - lib/view/modelgui.html
      - lib/view/marketview/marketview.html
      - lib/view/controlbar/controlbar.html
- $dart2js:
    suppressWarnings: false
